### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by andrepacak** [pluto-build/build-java#2]
In line 132 of the JavaBuilder.java 
FileCommands.replaceExtension(FileCommands.getRelativePath(targetDir, p), "java")
gets called. But there occurs a NullPointerException inside of replaceExtension.
The inputs for FileCommands.getRelativePath are File objects with the followings paths:
targetDir = /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsbj
p = /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsbj/monto/service/ast/AST.class

**Comment by seba--** [comment]
I cannot reproduce this error with FileCommands from common version 1.5.0-snapshot. But I noticed that build-java requires common 1.4.1-snapshot. I updated this requirement to 1.5.0. Can you check if this fixes the error?

(the latest version of common is here https://github.com/sugar-lang/common/tree/maven)

**Comment by andiderp** [comment]
The Exception still occurs. Maybe the FileCommands.getRelativePath returns null.

**Comment by andrepacak** [comment]
I now called .getAbsoluteFile() on every file that the JavaBuilder needs as input. But there is another NullPointerException.

Compile Java files AST.java
    Compile Java files IRegion.java ... succeeded - 626ms
    Compile Java files ASTVisitor.java
      Compile Java files NonTerminal.java
        Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsbj/monto/service/ast/AST.dep
        Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java ... Cycle building failed: null - 3ms
      Compile Java files NonTerminal.java ... done - 739ms
    Compile Java files ASTVisitor.java ... class java.lang.NullPointerException: null - 1379ms
java.lang.NullPointerException
    at build.pluto.builder.Builder.requireBuild(Builder.java:214)
    at build.pluto.buildjava.JavaBuilder.buildAll(JavaBuilder.java:103)
    at build.pluto.builder.BuildAtOnceCycleHandler.buildCycle(BuildAtOnceCycleHandler.java:57)
    at build.pluto.builder.CycleHandler.buildCycle(CycleHandler.java:67)
    at build.pluto.builder.BuildManager.tryCompileCycle(BuildManager.java:175)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:113)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.BuildCycleAtOnceBuilder.requireBuild(BuildCycleAtOnceBuilder.java:104)
    at build.pluto.buildjava.JavaBuilder.lambda$buildAll$5(JavaBuilder.java:123)
    at build.pluto.buildjava.JavaBuilder$$Lambda$41/673324818.action(Unknown Source)
    at build.pluto.buildjava.JavaBuilder.buildAll(JavaBuilder.java:135)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:114)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:17)
    at build.pluto.builder.Builder.triggerBuild(Builder.java:118)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:107)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.BuildCycleAtOnceBuilder.requireBuild(BuildCycleAtOnceBuilder.java:104)
    at build.pluto.buildjava.JavaBuilder.lambda$buildAll$5(JavaBuilder.java:123)
    at build.pluto.buildjava.JavaBuilder$$Lambda$41/673324818.action(Unknown Source)
    at build.pluto.buildjava.JavaBuilder.buildAll(JavaBuilder.java:135)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:114)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:17)
    at build.pluto.builder.Builder.triggerBuild(Builder.java:118)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:107)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.Builder.requireBuild(Builder.java:197)
    at build.pluto.builder.Builder.requireBuild(Builder.java:175)
    at build.pluto.buildmonto.ServicesBaseJavaBuilder.build(ServicesBaseJavaBuilder.java:97)
    at build.pluto.buildmonto.ServicesBaseJavaBuilder.build(ServicesBaseJavaBuilder.java:33)
    at build.pluto.builder.Builder.triggerBuild(Builder.java:118)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:107)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.BuildManager.requireInitially(BuildManager.java:261)
    at build.pluto.builder.BuildManagers.build(BuildManagers.java:62)
    at build.pluto.builder.BuildManagers.build(BuildManagers.java:57)
    at build.pluto.cli.Main.main(Main.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
  Compile Java files AST.java ... Required builder failed. Error occurred in build step "Compile Java files NonTerminal.java": null - 2624ms
Build monto:services-base-java ... Required builder failed. Error occurred in build step "Compile Java files NonTerminal.java": null - 2931ms
build.pluto.builder.RequiredBuilderFailed: Required builder failed. Error occurred in build step "Compile Java files NonTerminal.java": null
    at build.pluto.builder.RequiredBuilderFailed.init(RequiredBuilderFailed.java:59)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:130)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.BuildCycleAtOnceBuilder.requireBuild(BuildCycleAtOnceBuilder.java:104)
    at build.pluto.buildjava.JavaBuilder.lambda$buildAll$5(JavaBuilder.java:123)
    at build.pluto.buildjava.JavaBuilder$$Lambda$41/673324818.action(Unknown Source)
    at build.pluto.buildjava.JavaBuilder.buildAll(JavaBuilder.java:135)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:114)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:17)
    at build.pluto.builder.Builder.triggerBuild(Builder.java:118)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:107)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.BuildCycleAtOnceBuilder.requireBuild(BuildCycleAtOnceBuilder.java:104)
    at build.pluto.buildjava.JavaBuilder.lambda$buildAll$5(JavaBuilder.java:123)
    at build.pluto.buildjava.JavaBuilder$$Lambda$41/673324818.action(Unknown Source)
    at build.pluto.buildjava.JavaBuilder.buildAll(JavaBuilder.java:135)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:114)
    at build.pluto.builder.BuildCycleAtOnceBuilder.build(BuildCycleAtOnceBuilder.java:17)
    at build.pluto.builder.Builder.triggerBuild(Builder.java:118)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:107)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.Builder.requireBuild(Builder.java:197)
    at build.pluto.builder.Builder.requireBuild(Builder.java:175)
    at build.pluto.buildmonto.ServicesBaseJavaBuilder.build(ServicesBaseJavaBuilder.java:97)
    at build.pluto.buildmonto.ServicesBaseJavaBuilder.build(ServicesBaseJavaBuilder.java:33)
    at build.pluto.builder.Builder.triggerBuild(Builder.java:118)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:107)
    at build.pluto.builder.BuildManager.require(BuildManager.java:326)
    at build.pluto.builder.BuildManager.requireInitially(BuildManager.java:261)
    at build.pluto.builder.BuildManagers.build(BuildManagers.java:62)
    at build.pluto.builder.BuildManagers.build(BuildManagers.java:57)
    at build.pluto.cli.Main.main(Main.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at build.pluto.builder.Builder.requireBuild(Builder.java:214)
    at build.pluto.buildjava.JavaBuilder.buildAll(JavaBuilder.java:103)
    at build.pluto.builder.BuildAtOnceCycleHandler.buildCycle(BuildAtOnceCycleHandler.java:57)
    at build.pluto.builder.CycleHandler.buildCycle(CycleHandler.java:67)
    at build.pluto.builder.BuildManager.tryCompileCycle(BuildManager.java:175)
    at build.pluto.builder.BuildManager.executeBuilder(BuildManager.java:113)
    ... 36 more

**Comment by seba--** [comment]
Can you try to provide a reproducible error description? Here is the code that I tried following your first comment:

```
String targetDir = "/Users/andiderp/repos/pluto-ecosystem/build-monto/targetsbj";
String p = "/Users/andiderp/repos/pluto-ecosystem/build-monto/targetsbj/monto/service/ast/AST.class";
Path rel = getRelativePath(new File(targetDir), new File(p));
System.out.println(replaceExtension(rel, "java"));
```

How to modify this code in order to reproduce the error?

**Comment by andrepacak** [comment]
For which method? requireBuild?

The problem here is that in Builder::requireBuild we try to call result.requires but result is null, which is of type BuildUnit.

**Comment by seba--** [comment]
Let's first fix the error before you called `getAbsoluteFile` everywhere. You reported an error in `replaceExtension(getRelativePath(...), ...)`.

**Comment by andrepacak** [comment]
``` java
String targetDir = "targetsbj";
String p = "/Users/andiderp/repos/pluto-ecosystem/build-monto/targetsbj/monto/service/ast/AST.class";
Path rel = getRelativePath(new File(targetDir), new File(p));
System.out.println(replaceExtension(rel, "java"));
```

It makes sense that the getRelativePath returns null.

**Comment by seba--** [comment]
Fixed https://github.com/sugar-lang/common/commit/588f28cee0cd7bf6a42b95b9ea76b97bcd1da41d

Paths are now relativized by making them absolute first
